/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dell' at '17-6-1 上午8:24' with Gradle 2.14
 *
 * @author dell, @date 17-6-1 上午8:24
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
